### ISSUE TITLE
SD trades with Sacramento

### ISSUE THREAD

**Issue by calvingoc** [calvingoc/The-Beazus-League#100]
![Screenshot from 2020-02-10 11-21-22](https://user-images.githubusercontent.com/24964401/74173422-b2faaf00-4bf7-11ea-9a5a-f8da5855f80c.png)
I get a great player on a great deal and some small draft comp for a good player on an expiring a really promising young player (3rd pick in the last draft) this year's first and taking off a huge but expiring deal for an old bad player. The net deal though is SD gets the best player in the deal but SAC gets depth they desperately need and open up 6M of cap space this year they can use for more depth.

**Comment by nemogoc** [comment]
That IS a shockingly terrible contract you're taking back, but it is expiring, so that doesn't help them, that helps you (you can spend that money in FA this offseason). If I can reframe your sell of this:

I get a great player on a great deal, plus spending power next offseason in exchange for a 1 year rental of a good player and a non-lottery first.

**Comment by calvingoc** [comment]
going to push back a little on this as I am going to have a lot of cap space this summer with or without the trade so it isn't like this is unlocking my ability to spend. This may be sinking any chance of this trade but I see it as similar to the Thunder dealing Harden for depth. You found out the hard way that you can't win with only good starters which is where SAC is right now, this trade would give them playable depth without a massive downgrade of their starters.

**Comment by nemogoc** [comment]
I'll wait to say more until Nick has a chance to see it.

**Comment by calvingoc** [comment]
while these numbers are a little skewed from injuries right now SAC has a 43 playing 25 mins, 40 playing 22.5, 43 playing 21.2 and a 36 playing 17 minutes. After the trade they could give the 40 and 36's playing time to a 51 and a 26, plus have space to more upgrades
