### ISSUE TITLE
Cheesesteak Roster adjustment

### ISSUE THREAD

**Issue by Beefsworth** [calvingoc/The-Beazus-League#2]
Put Emerson Davis into the 5th starter spot, and put C.J. Frazier into the top bench spot. Roster should look like this: 
![image](https://user-images.githubusercontent.com/53273065/62147076-5f102480-b2bc-11e9-82d6-391957357d1d.png)

**Comment by calvingoc** [comment]
I'm starting Maker instead as with the rebounding he is better than Davis

**Comment by Beefsworth** [comment]
Please put Emerson Davis in for Maker, even with the rebounding update I'd rather have Davis at center.
