### ISSUE TITLE
Oglesby for Picks

### ISSUE THREAD

**Issue by nemogoc** [calvingoc/The-Beazus-League#31]
Approved by the AI

![image](https://user-images.githubusercontent.com/1668286/66137914-6b1da880-e5c3-11e9-9ffe-ea03a795e4dd.png)

**Comment by calvingoc** [comment]
Probably better for you but this is acceptable.

**Comment by calvingoc** [comment]
![Screenshot from 2019-10-03 10-22-22](https://user-images.githubusercontent.com/24964401/66140444-bcc83200-e5c7-11e9-928f-d1ec152ea889.png)
