### ISSUE TITLE
Sewell salary dump

### ISSUE THREAD

**Issue by nemogoc** [calvingoc/The-Beazus-League#32]
Accepted by the AI

![image](https://user-images.githubusercontent.com/1668286/66138342-14649e80-e5c4-11e9-9767-cda0c12a54dd.png)

**Comment by calvingoc** [comment]
I vote no on this, the gold rush are 1-6 and are giving you a younger player who is similar to Bryce stat wise on a better contract and don't get anything of value in return.

**Comment by calvingoc** [comment]
![Screenshot from 2019-10-03 10-19-28](https://user-images.githubusercontent.com/24964401/66140201-517e6000-e5c7-11e9-9edd-6ef93a28ac1b.png)

**Comment by nemogoc** [comment]
Modified to just sewell for golubic, plus I threw in seattle's 2022 2nd
