### ISSUE TITLE
Armstrong for picks

### ISSUE THREAD

**Issue by nemogoc** [calvingoc/The-Beazus-League#34]
Accepted by the AI

![image](https://user-images.githubusercontent.com/1668286/66138921-17ac5a00-e5c5-11e9-8ed4-312a50120198.png)

**Comment by calvingoc** [comment]
I don't know how they are 6-1 right now the bums are bad, they are starting a 48!! I don't like this trade but if Nick things its passable I'll allow it.

**Comment by calvingoc** [comment]
![Screenshot from 2019-10-03 10-20-29](https://user-images.githubusercontent.com/24964401/66140288-75da3c80-e5c7-11e9-9ee7-1816a665fedf.png)
