### ISSUE TITLE
K&B BigChumpy trade

### ISSUE THREAD

**Issue by Beefsworth** [calvingoc/The-Beazus-League#40]
![image](https://user-images.githubusercontent.com/53273065/66240389-2593d500-e6c2-11e9-9726-ff94e4d861ac.png)

**Comment by calvingoc** [comment]
I'm vetoing this trade as is. If you just want to do a straight player swap I would allow it. But they are giving up assets on an already not good player swap.

**Comment by Beefsworth** [comment]
I'd do the 1 for 1 Chumpy -> Salvi trade: 
https://i.imgur.com/5OhFpJt.jpg
