### ISSUE TITLE
K&B Cheesesteaks Signing 3 Free Agents

### ISSUE THREAD

**Issue by Beefsworth** [calvingoc/The-Beazus-League#49]
Here are the three free agents I'd like to sign to a one-year minimum contract.
![image](https://user-images.githubusercontent.com/53273065/67717407-a3828d80-f99b-11e9-8949-c8453a3b2f8b.png)

**Comment by calvingoc** [comment]
you got jones but the swamp dragons matched for the other 2 and as the worse team they get the players
