### ISSUE TITLE
SD trade with BAL

### ISSUE THREAD

**Issue by calvingoc** [calvingoc/The-Beazus-League#60]
![Screenshot from 2019-11-19 12-09-40](https://user-images.githubusercontent.com/24964401/69173505-871ed000-0ac5-11ea-904a-e37675ed92e4.png)
The dragons get a future 1st and the crabs get off money next year to resign poopy, get first signing rights on cousins and get two seconds.

**Comment by nemogoc** [comment]
Fine with me
