### ISSUE TITLE
K&B Restricted FA Signings: Megathon Maker

### ISSUE THREAD

**Issue by Beefsworth** [calvingoc/The-Beazus-League#62]
![image](https://user-images.githubusercontent.com/53273065/69248742-6d879200-0b72-11ea-8b5e-0d124ed24489.png)

I will accept these terms and bring Megathon back.

**Comment by nemogoc** [comment]
Obviously stuff like this isn't subject to veto (nor would I), but wow, eager really helps, that's a great deal.

**Comment by calvingoc** [comment]
I would also sign that but I don't think its anything crazy. The Mehdi contract is the crazy one
